export const CountryList = [
    { name: 'Afghanistan', flag: '🇦🇫', code: 'AF' },
    { name: 'Albania', flag: '🇦🇱', code: 'AL' },
    { name: 'Algeria', flag: '🇩🇿', code: 'DZ' },
    { name: 'Argentina', flag: '🇦🇷', code: 'AR' },
    { name: 'Australia', flag: '🇦🇺', code: 'AU' },
    { name: 'Austria', flag: '🇦🇹', code: 'AT' },
    { name: 'Bangladesh', flag: '🇧🇩', code: 'BD' },
    { name: 'Belgium', flag: '🇧🇪', code: 'BE' },
    { name: 'Brazil', flag: '🇧🇷', code: 'BR' },
    { name: 'Canada', flag: '🇨🇦', code: 'CA' },
    { name: 'China', flag: '🇨🇳', code: 'CN' },
    { name: 'Colombia', flag: '🇨🇴', code: 'CO' },
    { name: 'Denmark', flag: '🇩🇰', code: 'DK' },
    { name: 'Egypt', flag: '🇪🇬', code: 'EG' },
    { name: 'Finland', flag: '🇫🇮', code: 'FI' },
    { name: 'France', flag: '🇫🇷', code: 'FR' },
    { name: 'Germany', flag: '🇩🇪', code: 'DE' },
    { name: 'Ghana', flag: '🇬🇭', code: 'GH' },
    { name: 'Greece', flag: '🇬🇷', code: 'GR' },
    { name: 'India', flag: '🇮🇳', code: 'IN' },
    { name: 'Indonesia', flag: '🇮🇩', code: 'ID' },
    { name: 'Iran', flag: '🇮🇷', code: 'IR' },
    { name: 'Iraq', flag: '🇮🇶', code: 'IQ' },
    { name: 'Ireland', flag: '🇮🇪', code: 'IE' },
    { name: 'Israel', flag: '🇮🇱', code: 'IL' },
    { name: 'Italy', flag: '🇮🇹', code: 'IT' },
    { name: 'Japan', flag: '🇯🇵', code: 'JP' },
    { name: 'Kenya', flag: '🇰🇪', code: 'KE' },
    { name: 'Malaysia', flag: '🇲🇾', code: 'MY' },
    { name: 'Mexico', flag: '🇲🇽', code: 'MX' },
    { name: 'Morocco', flag: '🇲🇦', code: 'MA' },
    { name: 'Nepal', flag: '🇳🇵', code: 'NP' },
    { name: 'Netherlands', flag: '🇳🇱', code: 'NL' },
    { name: 'New Zealand', flag: '🇳🇿', code: 'NZ' },
    { name: 'Nigeria', flag: '🇳🇬', code: 'NG' },
    { name: 'Norway', flag: '🇳🇴', code: 'NO' },
    { name: 'Pakistan', flag: '🇵🇰', code: 'PK' },
    { name: 'Philippines', flag: '🇵🇭', code: 'PH' },
    { name: 'Poland', flag: '🇵🇱', code: 'PL' },
    { name: 'Portugal', flag: '🇵🇹', code: 'PT' },
    { name: 'Qatar', flag: '🇶🇦', code: 'QA' },
    { name: 'Russia', flag: '🇷🇺', code: 'RU' },
    { name: 'Saudi Arabia', flag: '🇸🇦', code: 'SA' },
    { name: 'Singapore', flag: '🇸🇬', code: 'SG' },
    { name: 'South Africa', flag: '🇿🇦', code: 'ZA' },
    { name: 'South Korea', flag: '🇰🇷', code: 'KR' },
    { name: 'Spain', flag: '🇪🇸', code: 'ES' },
    { name: 'Sri Lanka', flag: '🇱🇰', code: 'LK' },
    { name: 'Sweden', flag: '🇸🇪', code: 'SE' },
    { name: 'Switzerland', flag: '🇨🇭', code: 'CH' },
    { name: 'Thailand', flag: '🇹🇭', code: 'TH' },
    { name: 'Turkey', flag: '🇹🇷', code: 'TR' },
    { name: 'Ukraine', flag: '🇺🇦', code: 'UA' },
    { name: 'United Arab Emirates', flag: '🇦🇪', code: 'AE' },
    { name: 'United Kingdom', flag: '🇬🇧', code: 'GB' },
    { name: 'United States', flag: '🇺🇸', code: 'US' },
    { name: 'Vietnam', flag: '🇻🇳', code: 'VN' },
];
